import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import RegisterModal from "./components/modals/RegisterModal";
import { Toaster } from "react-hot-toast";
import { getCurrentUser } from "./actions/getCurrentUser";
import LoginModal from "./components/modals/LoginModal";
import AddProjectModal from "./components/modals/AddProjectModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <RegisterModal />
        <AddProjectModal />
        <LoginModal />
        <Toaster />
        <Navbar currentUser={currentUser} />
        <hr />
        {children}
      </body>
    </html>
  );
}
